import { getAppInstance } from './app-instance.js';

export async function renderDashboardPage() {
  const app = await getAppInstance();
  const dashboard = await app.renderDashboard();
  const pageScript = [
    '(function(){',
    'const statusEl=document.getElementById("control-status");',
    'const setStatus=(msg,isError)=>{if(!statusEl)return;statusEl.textContent=msg||"";statusEl.style.color=isError?"#b03a48":"#2d5b86";};',
    'const settingsForm=document.getElementById("settings-form");',
    'if(settingsForm){settingsForm.addEventListener("submit",async(e)=>{e.preventDefault();',
    'const entryId=Number(document.getElementById("entry-id")?.value||0);',
    'const channelsRaw=String(document.getElementById("channel-ids")?.value||"");',
    'const channels=channelsRaw.split(/\\n|,/).map(v=>v.trim()).filter(Boolean);',
    'if(!entryId||channels.length===0){setStatus("Entry ID and at least one channel are required.",true);return;}',
    'setStatus("Saving settings...",false);',
    'try{const res=await fetch("/api/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({entry_id:entryId,channels})});',
    'if(!res.ok){throw new Error("settings_failed");}',
    'setStatus("Settings saved.",false);setTimeout(()=>window.location.reload(),400);}catch(err){setStatus("Failed to save settings.",true);}});}',
    'const syncBtn=document.getElementById("sync-now");',
    'if(syncBtn){syncBtn.addEventListener("click",async()=>{setStatus("Running sync...",false);',
    'try{const res=await fetch("/api/sync/run",{method:"POST"});if(!res.ok){throw new Error("sync_failed");}',
    'setStatus("Sync completed. Refreshing...",false);setTimeout(()=>window.location.reload(),700);}catch(err){setStatus("Sync failed. Check CRON_SECRET/auth.",true);}});}',
    '})();',
  ].join('');
  const styles = [
    ':root{--ink:#0b1320;--muted:#42526b;--bg:#eef3f8;--panel:#ffffff;--line:#d8e1eb;--buy:#0f8a5f;--sell:#b03a48;--hold:#48617b;}',
    '*{box-sizing:border-box;}',
    'body{margin:0;font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;background:radial-gradient(circle at top,#f8fbff,#e7eef7 55%,#e1e9f3 100%);color:var(--ink);}',
    '.page-wrap{max-width:1120px;margin:0 auto;padding:32px 20px 56px;}',
    '.hero{display:flex;justify-content:space-between;align-items:end;gap:16px;flex-wrap:wrap;margin-bottom:22px;}',
    '.hero h1{margin:0;font-size:2rem;letter-spacing:.2px;}',
    '.hero p{margin:8px 0 0;color:var(--muted);max-width:720px;}',
    '.run-chip{padding:8px 12px;border:1px solid var(--line);border-radius:999px;background:var(--panel);font-size:.85rem;color:var(--muted);}',
    '.radar-shell{background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:18px 16px 16px;box-shadow:0 8px 24px rgba(15,40,80,.06);}',
    '.radar-shell h1{margin:4px 0 0;font-size:1.25rem;}',
    '.radar-subtitle{margin:6px 0 16px;color:var(--muted);font-size:.95rem;}',
    '.radar-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;}',
    '.radar-column{border:1px solid var(--line);border-radius:12px;padding:12px;background:#fbfdff;}',
    '.radar-column h2{margin:0 0 10px;font-size:.95rem;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);}',
    '.radar-list{list-style:none;padding:0;margin:0;display:flex;flex-direction:column;gap:10px;}',
    '.radar-item{border:1px solid var(--line);border-radius:10px;padding:10px;background:#fff;}',
    '.radar-item-head{display:flex;justify-content:space-between;align-items:center;gap:8px;}',
    '.badge{padding:3px 8px;border-radius:999px;font-size:.8rem;background:#ecf3fb;color:#24486f;}',
    '.radar-item p{margin:8px 0 0;color:var(--muted);font-size:.9rem;}',
    '.empty{text-align:center;color:var(--muted);}',
    '.radar-column:nth-child(1) .badge{background:#e5f5ef;color:var(--buy);}',
    '.radar-column:nth-child(2) .badge{background:#fdecef;color:var(--sell);}',
    '.radar-column:nth-child(3) .badge{background:#ebf1f8;color:var(--hold);}',
    '.meta-grid{margin-top:14px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;}',
    '.meta-card{border:1px solid var(--line);border-radius:12px;padding:12px;background:#fff;}',
    '.meta-card h2{margin:0 0 10px;font-size:.95rem;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);}',
    '.meta-card p{margin:6px 0;color:var(--muted);}',
    '.meta-card code{font-size:.8rem;background:#f2f6fb;padding:2px 5px;border-radius:6px;}',
    '.control-card{background:#f9fbff;}',
    '.control-form{display:grid;gap:8px;}',
    '.control-form label{font-size:.86rem;color:var(--muted);font-weight:600;}',
    '.control-form input,.control-form textarea{width:100%;border:1px solid var(--line);border-radius:10px;padding:10px;font:inherit;background:#fff;}',
    '.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:4px;}',
    '.actions button{border:1px solid #0f8a5f;background:#0f8a5f;color:#fff;padding:8px 12px;border-radius:8px;cursor:pointer;font:inherit;}',
    '.actions .secondary{border-color:#24486f;background:#24486f;}',
    '.control-status{min-height:18px;margin-top:2px;font-size:.88rem;}',
    '.channel-list,.run-list{list-style:none;padding:0;margin:8px 0 0;display:flex;flex-direction:column;gap:8px;max-height:180px;overflow:auto;}',
    '.event-list{list-style:none;padding:0;margin:8px 0 0;display:flex;flex-direction:column;gap:10px;max-height:220px;overflow:auto;}',
    '.event-list li{border:1px solid var(--line);border-radius:10px;padding:8px;background:#fff;display:grid;gap:4px;}',
    '.event-list span{font-size:.8rem;color:var(--muted);}',
    '.wide{grid-column:1/-1;}',
    '.table-wrap{overflow:auto;}',
    'table{width:100%;border-collapse:collapse;font-size:.9rem;}',
    'th,td{text-align:left;border-bottom:1px solid var(--line);padding:8px 6px;vertical-align:top;}',
    'th{font-size:.78rem;text-transform:uppercase;letter-spacing:.4px;color:var(--muted);}',
    '@media (max-width:900px){.radar-grid{grid-template-columns:1fr;}}',
    '@media (max-width:900px){.meta-grid{grid-template-columns:1fr;}}',
  ].join('');

  return [
    '<!doctype html>',
    '<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FPL Transfer Radar</title>',
    `<style>${styles}</style>`,
    '</head>',
    '<body>',
    '<div class="page-wrap">',
    '<header class="hero">',
    '<div><h1>FPL Transfer Radar</h1><p>Track buy, sell, and hold signals from your configured channels and squad context.</p></div>',
    `<div class="run-chip">Updated ${new Date().toISOString()}</div>`,
    '</header>',
    dashboard,
    '</div>',
    `<script>${pageScript}</script>`,
    '</body></html>',
  ].join('');
}

export default async function Page() {
  return renderDashboardPage();
}
